import {
  User,
  Partner,
  ConnectionInfo,
  PrivacySettingItem,
  SharedNote,
  SharedPreference,
  SharedActivity,
  AppNotification,
  UserNotificationSettings,
} from '../types';

export const INITIAL_USER: User = {
  id: 'usr_98231',
  name: 'Alex Rivera',
  email: 'alex.rivera@example.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  partnerId: 'ptnr_44120',
  notificationSharingEnabled: false, // Default: OFF (strict user consent)
  shareCycleSupportInsights: false,  // Default: OFF (strict user consent)
  dateOfBirth: '1995-06-12',
  statusMessage: 'Focused on deep work this afternoon',
  timezone: 'UTC-5 (Eastern Time)',
  createdAt: '2024-01-15',
  accountStatus: 'active',
};

export const INITIAL_PARTNER: Partner = {
  id: 'ptnr_44120',
  name: 'Elena Chen',
  email: 'elena.chen@example.com',
  avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
  connectedAt: '2024-02-14',
  statusMessage: 'Traveling until Thursday • Available via message',
  timezone: 'UTC-8 (Pacific Time)',
  inviteCode: 'LUNA-7734-ELN',
};

export const INITIAL_CONNECTION: ConnectionInfo = {
  status: 'connected',
  partner: INITIAL_PARTNER,
  inviteCode: 'LUNA-9823-ALX',
  connectedSince: 'Feb 14, 2024',
  encryptionStatus: 'Active',
};

export const INITIAL_PRIVACY_SETTINGS: PrivacySettingItem[] = [
  {
    id: 'priv_1',
    category: 'profile',
    title: 'Profile Information',
    description: 'Allows your partner to view your profile photo, real name, status message, and local timezone.',
    isShared: true,
    partnerIsSharing: true,
    partnerVisibilityNotice: 'Elena can view your name, timezone & status message.',
    lastModified: 'Yesterday at 4:12 PM',
  },
  {
    id: 'priv_2',
    category: 'contact',
    title: 'Contact Information',
    description: 'Shares your direct personal phone number and private backup email address with your partner.',
    isShared: true,
    partnerIsSharing: true,
    partnerVisibilityNotice: 'Elena has permission to see your phone number and email.',
    lastModified: 'Feb 14, 2024',
  },
  {
    id: 'priv_3',
    category: 'notes',
    title: 'Shared Notes & Documents',
    description: 'Grants access to create, read, and edit mutual notes, checklists, and saved locations in the Shared Space.',
    isShared: true,
    partnerIsSharing: true,
    partnerVisibilityNotice: 'Both participants can view and contribute to shared notes.',
    lastModified: '3 days ago',
  },
  {
    id: 'priv_4',
    category: 'activity',
    title: 'Activity & Presence Indicators',
    description: 'Displays when you were last active in LunaLink and when you view or update shared items.',
    isShared: false,
    partnerIsSharing: false,
    partnerVisibilityNotice: 'Currently private. Elena does not see your online presence or read receipts.',
    lastModified: 'May 10, 2024',
  },
  {
    id: 'priv_5',
    category: 'preferences',
    title: 'Personal Preferences & Wishlist',
    description: 'Shares key dietary restrictions, personal preferences, and mutual reminder bookmarks.',
    isShared: true,
    partnerIsSharing: true,
    partnerVisibilityNotice: 'Elena can see your saved preferences and favorite places.',
    lastModified: '1 week ago',
  },
];

export const INITIAL_SHARED_NOTES: SharedNote[] = [
  {
    id: 'note_1',
    title: 'Upcoming Travel Logistics & Flight Numbers',
    content: 'Outbound: Flight 824 departing 10:15 AM on the 24th. Elena confirmed confirmation code QX89P. Hotel reservation is under Chen. Remember passport check!',
    authorId: 'usr_98231',
    authorName: 'Alex Rivera',
    updatedAt: '2 hours ago',
    isPinned: true,
    category: 'plans',
  },
  {
    id: 'note_2',
    title: 'Apartment & Home Emergency Reference',
    content: 'Building access keycode: 4920#. Water shutoff valve is located in the basement hallway closet next to unit 2B. Wi-Fi router password in guest notes.',
    authorId: 'ptnr_44120',
    authorName: 'Elena Chen',
    updatedAt: 'Yesterday',
    isPinned: true,
    category: 'general',
  },
  {
    id: 'note_3',
    title: 'Favorite Quiet Coffee & Work Spots in the City',
    content: '1. Verve Coffee Roasters (great natural light, reliable power outlets)\n2. Blue Bottle on 4th (quieter after 2pm)\n3. Japanese Garden Tea House (offline reading)',
    authorId: 'usr_98231',
    authorName: 'Alex Rivera',
    updatedAt: '3 days ago',
    isPinned: false,
    category: 'places',
  },
  {
    id: 'note_4',
    title: 'Gift Ideas & Subtle Hints Archive',
    content: 'Elena mentioned wanting the hardcover reissue of "Design Systems" by Alla Kholmatova, and roasted hazelnut pour-over beans.',
    authorId: 'usr_98231',
    authorName: 'Alex Rivera',
    updatedAt: '1 week ago',
    isPinned: false,
    category: 'favorites',
  },
];

export const INITIAL_SHARED_PREFERENCES: SharedPreference[] = [
  {
    id: 'pref_1',
    title: 'Dietary & Nutrition',
    category: 'Wellness',
    myValue: 'Vegetarian, mild lactose sensitivity',
    partnerValue: 'Pescatarian, no cilantro',
    updatedAt: 'May 2, 2024',
  },
  {
    id: 'pref_2',
    title: 'Travel Seating Preference',
    category: 'Travel',
    myValue: 'Window seat, forward cabin',
    partnerValue: 'Aisle seat, middle cabin',
    updatedAt: 'Apr 18, 2024',
  },
  {
    id: 'pref_3',
    title: 'Quiet Hours / Do Not Disturb',
    category: 'Communication',
    myValue: '10:30 PM - 7:00 AM (EST)',
    partnerValue: '11:00 PM - 7:30 AM (PST)',
    updatedAt: '3 weeks ago',
  },
  {
    id: 'pref_4',
    title: 'Emergency Contact Contacted First',
    category: 'Safety',
    myValue: 'Dr. Rivera (Father) • +1 (555) 304-9128',
    partnerValue: 'David Chen (Brother) • +1 (555) 891-2390',
    updatedAt: 'Feb 15, 2024',
  },
];

export const INITIAL_ACTIVITIES: SharedActivity[] = [
  {
    id: 'act_1',
    type: 'note_created',
    title: 'Shared note added',
    description: 'Added "Weekend Itinerary & Flight Details" to your shared space',
    actorName: 'Alex Rivera',
    timestamp: '2 hours ago',
  },
  {
    id: 'act_2',
    type: 'privacy_updated',
    title: 'Privacy setting updated',
    description: 'Calendar & Availability visibility updated to Shared with partner',
    actorName: 'Alex Rivera',
    timestamp: 'Yesterday at 4:15 PM',
  },
  {
    id: 'act_3',
    type: 'connection_event',
    title: 'Partner connection accepted',
    description: 'Elena accepted the invite. Encrypted 1-to-1 corridor active.',
    actorName: 'System',
    timestamp: 'Feb 14, 2024',
  },
  {
    id: 'act_4',
    type: 'preference_updated',
    title: 'Preference updated',
    description: 'Travel seating preference updated to Window seat',
    actorName: 'Elena Chen',
    timestamp: 'May 10, 2024',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  // 1. UPCOMING_SUPPORT: A potentially higher-support day may be approaching
  {
    id: 'notif_pred_upcoming_1',
    type: 'UPCOMING_SUPPORT',
    predictiveType: 'UPCOMING_SUPPORT',
    category: 'insights',
    title: '🌙 A support day may be approaching',
    message: 'Based on previous cycle patterns, she may appreciate some extra support in the next couple of days.',
    discreetMessage: 'A supportive window may be approaching in ~2 days.',
    timestamp: '1 hour ago',
    isRead: false,
    actionUrl: 'support-insights',
    actionText: 'View Support Window',
    containsHealthData: false,
    reason: 'This notification is based on her previous cycle history. It is an estimate, not a medical prediction.',
    factors: [
      'Your previous cycle lengths (averaged ~28 days)',
      'Your recorded period history across recent cycles',
      'Comfort preferences from your Care Profile',
    ],
    privacyLevel: 'shared_with_partner',
    careSuggestions: [
      'Check in once',
      'Give her some space',
      'Offer her a warm drink',
      'Listen rather than giving advice',
    ],
    targetAudience: 'partner',
  },
  // 2. DAY_1_SUPPORT: Today may be a higher-support day
  {
    id: 'notif_pred_day1_1',
    type: 'DAY_1_SUPPORT',
    predictiveType: 'DAY_1_SUPPORT',
    category: 'care',
    title: '🌙 Today may be a higher-support day',
    message: 'Today is Day 1 of her cycle. Based on her previous patterns, she may appreciate some extra support.',
    discreetMessage: 'Day 1 support window: extra rest & care recommended.',
    timestamp: 'Today at 8:30 AM',
    isRead: false,
    actionUrl: 'care-mode',
    actionText: 'View Care Suggestions',
    containsHealthData: false,
    reason: 'This notification is based on her recorded period start date and previous cycle history. It is an estimate, not a medical prediction.',
    factors: [
      'Recorded period start date (Day 1)',
      'Previous cycle timing intervals',
      'Selected Care Profile preferences',
    ],
    privacyLevel: 'shared_with_partner',
    careSuggestions: [
      'Check in once gently',
      'A warm drink may help',
      'Keep a heating pad handy',
      'Listen rather than giving advice',
    ],
    targetAudience: 'partner',
  },
  // 3. CARE_MODE: She has activated Care Mode
  {
    id: 'notif_care_1',
    type: 'CARE_MODE',
    predictiveType: 'CARE_MODE',
    category: 'care',
    title: '🌙 She has activated Care Mode',
    message: 'Care Mode is active. Preferences requested: Warm drink, Quiet rest, and Heating pad.',
    discreetMessage: 'Care Mode is active. Check in gently with partner.',
    timestamp: '20 minutes ago',
    isRead: false,
    actionUrl: 'care-mode',
    actionText: 'View Care Mode',
    containsHealthData: false,
    reason: 'Activated directly by her in LunaLink to signal immediate comfort needs.',
    factors: [
      'Direct user Care Mode toggle',
      'Saved comfort preferences',
    ],
    privacyLevel: 'shared_with_partner',
    careSuggestions: [
      'Offer a warm drink or tea',
      'Keep the room quiet and comfortable',
      'Provide heating pad if needed',
      'Give her unhurried rest',
    ],
    targetAudience: 'partner',
  },
  // 4. SHARED_REMINDER: You have a shared reminder
  {
    id: 'notif_sh_1',
    type: 'SHARED_REMINDER',
    predictiveType: 'SHARED_REMINDER',
    category: 'shared',
    title: '🌙 You have a shared reminder',
    message: 'Alex scheduled "Restock Peppermint Tea & Heating Pad" for Friday.',
    timestamp: '4 hours ago',
    isRead: false,
    actionUrl: 'shared-calendar',
    actionText: 'Open Calendar',
    containsHealthData: false,
    reason: 'Created collaboratively in the Shared Calendar.',
    factors: ['Shared Calendar schedule'],
    privacyLevel: 'shared_with_partner',
    careSuggestions: [
      'Pick up tea from the grocery store',
      'Confirm heating pad location',
    ],
    targetAudience: 'user',
  },
  // 5. CARE_SUGGESTION: Here are some ways you can support her
  {
    id: 'notif_sugg_1',
    type: 'CARE_SUGGESTION',
    predictiveType: 'CARE_SUGGESTION',
    category: 'care',
    title: '🌙 Here are some ways you can support her',
    message: 'Here are personalized suggestions derived from her permitted Care Profile preferences.',
    timestamp: 'Yesterday at 5:00 PM',
    isRead: true,
    actionUrl: 'care-suggestions',
    actionText: 'Open Suggestions',
    containsHealthData: false,
    reason: 'Suggested based on permitted preferences saved in her Care Profile.',
    factors: ['Care Profile communication and comfort preferences'],
    privacyLevel: 'shared_with_partner',
    careSuggestions: [
      'Check in once',
      'Give her some space',
      'Offer her a warm drink',
      'Listen rather than giving advice',
    ],
    targetAudience: 'partner',
  },
  // Additional shared memory & privacy items
  {
    id: 'notif_sh_2',
    type: 'shared_memory',
    category: 'shared',
    title: 'New Shared Moment Added',
    message: 'Alex added a new memory to the Vault: "Rainy Sunday Lavender Tea".',
    timestamp: 'Yesterday at 7:30 PM',
    isRead: false,
    actionUrl: 'memory-vault',
    actionText: 'Open Memory Vault',
    containsHealthData: false,
    reason: 'Added to the private two-person Memory Vault.',
    privacyLevel: 'shared_with_partner',
  },
  {
    id: 'notif_priv_1',
    type: 'privacy_change',
    category: 'privacy',
    title: 'Sharing Permission Changed',
    message: 'Cycle Calendar visibility was switched to Private. Only non-health reminders are currently shared.',
    timestamp: '2 days ago',
    isRead: true,
    actionUrl: 'privacy-sharing',
    actionText: 'Audit Permissions',
    containsHealthData: false,
    reason: 'Privacy setting updated by user.',
    privacyLevel: 'private',
  },
  // CARE: Support reminder
  {
    id: 'notif_care_2',
    type: 'care_support_reminder',
    category: 'care',
    title: 'Gentle Support Check-in',
    message: 'Friendly reminder to take a 10-minute quiet break and hydrate with electrolytes.',
    timestamp: '3 days ago',
    isRead: true,
    actionUrl: 'care-suggestions',
    actionText: 'View Suggestions',
    containsHealthData: false,
  },
  // CARE: Care Mode turned off
  {
    id: 'notif_care_3',
    type: 'care_mode_deactivated',
    category: 'care',
    title: 'Care Mode Turned Off',
    message: 'Care Mode was gently turned off. Normal daily routine resumed.',
    timestamp: '5 days ago',
    isRead: true,
    actionUrl: 'care-mode',
    actionText: 'View History',
    containsHealthData: false,
  },
  // CONNECTION: Invitation accepted
  {
    id: 'notif_conn_1',
    type: 'partner_connected',
    category: 'connection',
    title: 'Partner Invitation Accepted',
    message: 'Elena accepted your connection invitation. Your private shared corridor is now active.',
    timestamp: '1 week ago',
    isRead: true,
    actionUrl: 'partner-profile',
    actionText: 'View Partner',
    containsHealthData: false,
  },
  // CONNECTION: Partner invitation
  {
    id: 'notif_conn_2',
    type: 'partner_invitation',
    category: 'connection',
    title: 'Partner Invitation Code Generated',
    message: 'Your invite code LUNA-9823-ALX is valid. Share it securely with your partner.',
    timestamp: '2 weeks ago',
    isRead: true,
    actionUrl: 'connect-partner',
    actionText: 'View Code',
    containsHealthData: false,
  },
];

export const DEFAULT_NOTIFICATION_SETTINGS: UserNotificationSettings = {
  partnerInvitation: true,
  invitationAccepted: true,
  careModeActivated: true,
  careModeDeactivated: true,
  supportReminders: true,
  sharedReminders: true,
  sharedMemories: true,
  sharedNotes: true,
  sharingPermissionChanged: true,
  supportPeriodApproaching: true,
  exposeHealthInfoInPreviews: false, // Strict privacy: do not expose health details in notification previews unless user turns this on
};

